name: Ops — GitHub Config

on:
  workflow_call:
    inputs:
      container-prefix:
        type: string
        required: false
        default: prod
        description: >-
          Container image name prefix (prod or dev). Defaults to "prod".
    secrets:
      APP_CLIENT_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true

permissions:
  contents: read

jobs:
  github-config:
    name: github-config
    runs-on: ubuntu-latest
    container: ghcr.io/vergil-project/${{ inputs.container-prefix || 'prod' }}-base:latest
    steps:
      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install vergil-tooling
        uses: vergil-project/vergil-actions/actions/shared/setup/vergil@v2.0.23

      - name: Audit GitHub configuration
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: vrg-github-repo-config audit --repo "${{ github.repository }}"
